# Generated by Django 6.0.5 on 2026-05-15 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescuerequest',
            name='user',
        ),
        migrations.AddField(
            model_name='cat',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='phone_number',
            field=models.CharField(default='temp', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='reporter_name',
            field=models.CharField(default='timezone.now', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.IntegerField(help_text='Age in months or years'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(default='temp', upload_to='cats/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('available', 'Available for Adoption'), ('rescued', 'Just Rescued'), ('medical', 'Under Medical Care'), ('adopted', 'Adopted')], default='rescued', max_length=20),
        ),
        migrations.AlterField(
            model_name='rescuerequest',
            name='description',
            field=models.TextField(help_text="Tell us about the cat's condition"),
        ),
        migrations.AlterField(
            model_name='rescuerequest',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rescuerequest',
            name='priority',
            field=models.CharField(choices=[('high', 'Emergency (Injured)'), ('medium', 'Urgent'), ('low', 'Normal')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='rescuerequest',
            name='status',
            field=models.BooleanField(default=False, help_text='Checked by team?'),
        ),
    ]
